import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from './theme/theme-provider';
import ThemeSwitcher from './components/ThemeSwitcher';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='ru' suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute='data-mode' defaultTheme='light'>
          <header className='flex justify-end w-full px-5 mx-auto max-w-screen-xl py-4'>
            <ThemeSwitcher />
          </header>

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
